name: .NET Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    env:
      SOLUTION_PATH: FixImporter.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore $env:SOLUTION_PATH

      - name: Build
        run: dotnet build $env:SOLUTION_PATH --configuration $env:CONFIGURATION --no-restore
        env:
          CONFIGURATION: ${{ matrix.configuration }}

  unit-tests:
    runs-on: windows-latest
    needs: build

    strategy:
      matrix:
        configuration: [Debug, Release]

    env:
      TEST_PROJECT_PATH: FixImporter.Tests/FixImporter.Tests.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run unit tests
        run: dotnet test $env:TEST_PROJECT_PATH --configuration $env:CONFIGURATION --verbosity normal
        env:
          CONFIGURATION: ${{ matrix.configuration }}

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t fiximporter:ci .

  discord:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v7.0.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
        content: "Test"

